name: Crash Report
description: Report a crash or unexpected termination
title: "[Crash]: "
labels: ["bug", "crash"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🛑 Stop! Before you submit
        Please perform these checks. **If these steps fail, your model file is corrupted, not the library.**

  - type: checkboxes
    id: rules
    attributes:
      label: Rules & Verification
      description: You must complete these steps before submitting.
      options:
        - label: I have verified that my local model SHA-256 hash matches the source on Hugging Face.
          required: true
        - label: I have tested this model with the [llama-cpp-model-tester](https://github.com/lookbe/llama-cpp-model-tester/releases/tag/model-tester) and it works fine.
          required: true
        - label: I understand that if these checks are not performed, my issue will be closed.
          required: true

  - type: input
    id: model_hash
    attributes:
      label: Model Hash
      placeholder: Paste your SHA-256 hash here...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      placeholder: |
        1. Load model...
        2. Execute command...
        3. See crash at...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs / Stack Trace
      description: Please paste the crash logs from your terminal.
      render: shell
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - Linux
        - macOS
    validations:
      required: true
