name: Bug Report
description: Report a crash or error in the library
title: "[Bug]: "
labels: ["bug"]
body:
  - type: checkboxes
    id: mandatory-checks
    attributes:
      label: Pre-submission Checklist
      description: Please complete these steps before submitting. Issues that fail these checks will be closed.
      options:
        - label: I have verified my model's SHA-256 hash matches the Hugging Face source.
          required: true
        - label: I have tested the model with [llama-cpp-model-tester](https://github.com/lookbe/llama-cpp-model-tester/releases/tag/model-tester) and it works fine there.
          required: true
        - label: I understand that if I provide insufficient information, my issue may be closed.
          required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      placeholder: A clear and concise description of what the crash/error is.
    validations:
      required: true

  - type: input
    id: model-info
    attributes:
      label: Model Name & Hash
      placeholder: e.g., Llama-3-8B-GGUF (Hash: a1b2c3d4...)
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      placeholder: |
        1. Load model '...'
        2. Set parameters '...'
        3. See crash at '...'
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs or Error Output
      description: Paste terminal logs or stack traces here.
      render: shell
